name: Build and Publish Native AOT

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            rid: win-x64
          - os: ubuntu-latest
            rid: linux-x64
          - os: macos-latest
            rid: osx-x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build ExampleGame AOT Binary
        run: >
          dotnet publish ExampleGame/ExampleGame.csproj
          -c Release
          -r ${{ matrix.rid }}
          /p:PublishSingleFile=true
          /p:StripSymbols=true

      - name: Upload Game Artifact
        uses: actions/upload-artifact@v4
        with:
          name: game-${{ matrix.rid }}
          path: ExampleGame/bin/Release/net8.0/${{ matrix.rid }}/publish/
